{
 "title": "MongoDB FTDC Analytics",
 "time": { "from": "2020-05-19T20:43:18.000Z", "to": "2020-05-20T15:43:16.000Z" },
 "panels": [
  {
   "title": "WiredTiger Cache",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "target": "wt_cache_max", "type": "timeserie" },
    { "target": "wt_cache_used", "type": "timeserie" },
    { "target": "wt_cache_dirty", "type": "timeserie" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "target": "mem_virtual", "type": "timeserie" },
    { "target": "mem_resident", "type": "timeserie" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "cpu_system", "type": "timeserie" },
    { "target": "cpu_user", "type": "timeserie" },
    { "target": "cpu_iowait", "type": "timeserie" },
    { "target": "cpu_nice", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "disks_iops", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Tickets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ticket_avail_read", "type": "timeserie" },
    { "target": "ticket_avail_write", "type": "timeserie" }
   ]
  },
  {
   "title": "Queued Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "q_queued_read", "type": "timeserie" },
    { "target": "q_queued_write", "type": "timeserie" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "conns_current", "type": "timeserie" },
    { "target": "conns_created/s", "type": "timeserie" },
    { "target": "conns_active", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "disks_utils", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Cache Pages Eviction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "wt_modified_evicted", "type": "timeserie" },
    { "target": "wt_unmodified_evicted", "type": "timeserie" }
   ]
  },
  {
   "title": "Ops In Progress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "q_active_read", "type": "timeserie" },
    { "target": "q_active_write", "type": "timeserie" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "latency_read", "type": "timeserie" },
    { "target": "latency_write", "type": "timeserie" },
    { "target": "latency_command", "type": "timeserie" }
   ]
  },
  {
   "title": "I/O In Progress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "disks_queue_length", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Cache",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "target": "wt_cache_read_in", "type": "timeserie" },
    { "target": "wt_cache_written_from", "type": "timeserie" }
   ]
  },
  {
   "title": "Query Executor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "scan_objects", "type": "timeserie" },
    { "target": "scan_keys", "type": "timeserie" },
    { "target": "op_blkSort", "type": "timeserie" },
    { "target": "op_writeConflicts", "type": "timeserie" }
   ]
  },
  {
   "title": "Ops Counters",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ops_query", "type": "timeserie" },
    { "target": "ops_insert", "type": "timeserie" },
    { "target": "ops_update", "type": "timeserie" },
    { "target": "ops_delete", "type": "timeserie" },
    { "target": "ops_getmore", "type": "timeserie" },
    { "target": "ops_command", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Read Wait Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "read_time_ms", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Block Manager",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "target": "wt_blkmgr_read", "type": "timeserie" },
    { "target": "wt_blkmgr_written", "type": "timeserie" },
    { "target": "wt_blkmgr_written_checkpoint", "type": "timeserie" }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "mem_page_faults", "type": "timeserie" }
   ]
  },
  {
   "title": "Network Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "net_requests", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Write Wait Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "write_time_ms", "type": "timeserie" }
   ]
  },
  {
   "title": "Host Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "targets": [
    { "target": "host_info", "type": "table" }
   ]
  },
  {
   "title": "Replication Lags",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "replication_lags", "type": "timeserie" }
   ]
  },
  {
   "title": "Network Bytes In/Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "target": "net_in", "type": "timeserie" },
    { "target": "net_out", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Total Wait Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "io_queued_ms", "type": "timeserie" }
   ]
  }
 ]
}