{
 "title": "MongoDB Disks Stats",
 "time": { "from": "2020-05-13T14:20:20.000Z", "to": "2020-05-13T21:20:18.000Z" },
 "panels": [
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "disks_iops", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "disks_utils", "type": "timeserie" }
   ]
  },
  {
   "title": "I/O In Progress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "disks_queue_length", "type": "timeserie" }
   ]
  },
  {
   "title": "Average Read Wait Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "read_time_ms", "type": "timeserie" }
   ]
  },
  {
   "title": "Average Write Wait Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "write_time_ms", "type": "timeserie" }
   ]
  },
  {
   "title": "Total Wait Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "io_queued_ms", "type": "timeserie" }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "latency_read", "type": "timeserie" },
    { "target": "latency_write", "type": "timeserie" },
    { "target": "latency_command", "type": "timeserie" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "cpu_iowait", "type": "timeserie" },
    { "target": "cpu_user", "type": "timeserie" }
   ]
  }
 ]
}